[cmd_duration]
format = "[󰔟](245) [$duration]($style) "

[env_var.SSH_AGENT_PID]
format = "[󰣀 ]($style)"
style = "yellow"

[env_var.SSH_AGENT_KEYS]
format = "[ ]($style)"
style = "yellow"

[os]
format = "[$symbol]($style)"
style = "purple"
disabled = false

[os.symbols]
Ubuntu = " "
Windows = " "

[shell]
bash_indicator = " "
fish_indicator = " "
format = "[$indicator]($style)"
disabled = false

[shlvl]
disabled = false
symbol = " "
threshold = 3
style="blue"
