[".config/fish/completions/eza.fish"]
type = "file"
url = "https://raw.githubusercontent.com/eza-community/eza/refs/heads/main/completions/fish/eza.fish"

[".config/fish/completions/nb.fish"]
type = "file"
url = "https://raw.githubusercontent.com/xwmx/nb/refs/heads/master/etc/nb-completion.fish"

[".local/bin/ansi"]
type = "file"
executable = true
url = "https://raw.githubusercontent.com/fidian/ansi/refs/heads/master/ansi"

[".local/bin/nb"]
type = "file"
executable = true
url = "https://raw.githubusercontent.com/xwmx/nb/refs/heads/master/nb"

[".local/share/complete-alias/complete-alias"]
type = "file"
url = "https://raw.githubusercontent.com/cykerway/complete-alias/refs/heads/master/complete_alias"

[".tmux"]
type = "archive"
url = "https://github.com/gpakosz/.tmux/archive/refs/heads/master.zip"
stripComponents = 1
