#theme = "monokai_pro_spectrum"
theme = "base16_transparent"

[editor]
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.statusline]
mode.normal = "N󰘳 "
mode.insert = "I "
mode.select = "S󰫙 "
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "none"
newline = "none"
