# For tmux, the host system needs: make, gcc, yacc, libncurses-dev
[tools]
"asdf:usage" = "latest"
bat = "latest"
chezmoi = "latest"
fzf = "latest"
gum = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
