# For tmux, the host system needs: make, gcc, yacc, libncurses-dev
[tools]
"asdf:usage" = "latest"
bat = "latest"
chezmoi = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
gitui = "latest"
gum = "latest"
helix = "latest"
jq = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "22"
"npm:readability-cli" = "latest"
pandoc = "latest"
pipx = "latest"
"pipx:buku" = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
zellij = "latest"
zoxide = "latest"
