# For tmux, the host system needs: make, gcc, yacc, libncurses-dev
[tools]
"asdf:usage" = "latest"
bat = "latest"
chezmoi = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gum = "latest"
neovim = "latest"
node = "22"
"npm:readability-cli" = "latest"
pandoc = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
zoxide = "latest"
